[project]
name = "switch_bot_app"
description = "switch bot app"
version = "0.1.0"
authors = [
    { name = "Roberto Serra", email = "obi.serra@gmail.com" }
]
dependencies = []

[project.optional-dependencies]
dev = []